webTiengAnh/Models/entity/BaiHoc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTiengAnh.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHoc
    {
        public int MaBH { get; set; }
        public string TenBH { get; set; }
        public string ChuDe { get; set; }
        public string AnhChuDe { get; set; }
        public string NoiDung { get; set; }
        public string NoiDungAnh { get; set; }
        public string NghiaTu { get; set; }
        public string NghiaTu2 { get; set; }
    }
}

webTiengAnh/Controllers/BaiHocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webTiengAnh.Models.entity;
using webTiengAnh.Models.DAO;
using webTiengAnh.Models.DTO;
using PagedList;

namespace webTiengAnh.Controllers
{
    public class BaiHocController : Controller
    {
        // GET: BaiHoc
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult QLBaiHoc(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                BaiHocDAO dao = new BaiHocDAO();
                IQueryable<BaiHoc> hs = dao.DanhSachBaiHoc();
                return View(hs.OrderBy(n => n.MaBH).ToPagedList(pageNumber, pageSize));
            }
        }
        public ActionResult SearchBaiHoc()
        {
            return View();
        }


        public ActionResult ThemBaiHoc()
        {
            return View();
        }
        public ActionResult AddBaiHoc(BaiHocDTO hsa)
        {
            BaiHocDAO dao = new BaiHocDAO();
            dao.ThemBH(hsa);
            return RedirectToAction("QLBaiHoc");
        }
        public ActionResult SuaBaiHoc(int id)
        {
            BaiHocDAO dao = new BaiHocDAO();
            BaiHoc bh = dao.FindBaiHocById(id);
            return View(bh);
        }
        public ActionResult EditActionBaiHoc(BaiHoc hsu)
        {
            BaiHocDAO dao = new BaiHocDAO();

            dao.SuaBH(hsu);
            return RedirectToAction("QLBaiHoc");
        }
        public ActionResult XoaBaiHoc(int id)
        {
            BaiHocDAO dao = new BaiHocDAO();
            //BaiHoc bh = dao.FindBaiHocById(id);
            dao.XoaBH(id);

            return RedirectToAction("QLBaiHoc");
        }
        public ActionResult ChiTietBH(int id)
        {
            
            var model = new BaiHocDAO().ListBHID(id);
            return View(model);
        }
        public JsonResult KiemTraNghia(string txt1, string txt2)
        {
            BaiHoc bh = new BaiHoc();
            //bh.NghiaTu = 
            BaiHocDAO dao = new BaiHocDAO();
            var kq = dao.Kiemtra(txt1, txt2);
            //kq = BaiHocDAO().Kiemtra(txt1, txt2);
            if (kq == 1)
            {
                return Json(new { status = true });
            }
            else
                return Json(new { status = false });
        }
    }
}

webTiengAnh/Views/BaiHoc/ChiTietBH.cshtml
@model List<webTiengAnh.Models.entity.BaiHoc>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ChiTietBH";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/Content/byme.css" rel="stylesheet" />

<style type="text/css">
    h2 {
        text-align: center;
        margin-bottom: 20px;
        width: 100%;
    }

    table {
        text-align: center;
        width: 100%;
        margin-bottom: 50px;
    }

    .all {
        width: 100%;
        text-align: center;
    }
</style>


<h2>Bài Học</h2>
<div class="all">

    <table>
        @foreach (var item in Model)
            {
            <tr class="baihoc">
                <td>
                    <h2>Tên Bài Học: @Html.DisplayFor(modelItem => item.TenBH)</h2>
                </td>

            </tr>
            <tr>
                <td>

                    <p> Chủ đề: @item.ChuDe</p>
                </td>
            </tr>
            if (item.TenBH == "Qua Hình Ảnh")
            {


                <tr>
                    <td>
                        <a href="/"><img src="@item.NoiDung" width="350px" height="350px" /></a>
                    </td>
                            @*@using (Html.BeginForm("KiemTraNghia", "BaiHoc"))
                            {
                                <td><ul>@Html.Label("Nhập nghĩa của từ")</ul> </td>
                                <td> <ul>@Html.TextBoxFor(m=> m.NghiaTu)</ul></td>
                            }*@
                    <td> <input name="nghia1" id="nghia1" type="text"placeholder="Nhập danh sách nghĩa của từ" /></td>
                    <td> <button value="Kiểm tra" id="btnkt"class="btn btn-circle ">Kiểm tra</button></td>
                </tr>
                <tr>
                    <td style="margin-top: 60px">
                        <a href="/"><img src="@item.NoiDungAnh" width="350px" height="350px" /></a>

                    </td>
                    <td> <input name="nghia2" id="nghia2" type="text" placeholder="Nhập danh sách nghĩa của từ" /></td>
                    <td> <button type="submit" value="Kiểm tra" id="btnkt2" class="btn btn-circle" >Kiểm tra</button></td>
                </tr>
                
            }
            else
            {
                <iframe width="560" height="315" src="@item.NoiDung" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> </iframe>
            }

        }
    </table>

</div>

webTiengAnh/Views/BaiHoc/QLBaiHoc.cshtml
@{
    ViewBag.Title = "QLBaiHoc";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@model PagedList.IPagedList<webTiengAnh.Models.entity.BaiHoc>
@using PagedList.Mvc;

<h2>Danh sách bài học</h2>
<div class="panel-body">
    @using (Html.BeginForm("SearchBaHoc", "BaiHoc"))
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-4">
                    <a type="button" class="btn btn-primary" href="/BaiHoc/ThemBaiHoc">Thêm bài học</a>
                </div>
                <div class="col-md-3">
                    <input type="text" name="searchString" placeholder="Tìm kiếm" />
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success"> Tìm kiếm</button>
                </div>
            </div>

        </div>
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Tên Bài Học")
        </th>
        <th>
            @Html.DisplayName("Chủ đề")
        </th>
        <th>
            @Html.DisplayName("Ảnh Chủ Đề")
        </th>
        <th>
            @Html.DisplayName("Nội Dung")
        </th>
        <th>
            @Html.DisplayName("Nội Dung Ảnh")
        </th>
        <th>
            @Html.DisplayName("Danh sách nghĩa từ")
        </th>
        <th>
            @Html.DisplayName("Danh sách nghĩa từ 2")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenBH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChuDe)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.AnhChuDe)*@
                <img src="@item.AnhChuDe" width="95px" height="95px"/>
            </td>
            @if (item.TenBH == "Qua Hình Ảnh")
            {
                <td>
                    <img src="@item.NoiDung" width="95px" height="95px" />
                </td>
                <td>
                    <img src="@item.NoiDungAnh" width="95px" height="95px" />
                </td>
            }
            else
            {
                <td>
                <iframe width="95" height="95" src="@item.NoiDung" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> </iframe>
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.NghiaTu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NghiaTu2)
            </td>
            <td>
                @Html.ActionLink("Sửa", "SuaBaiHoc", new { id = item.MaBH }) |

                @Html.ActionLink("Xóa", "XoaBaiHoc", new { id = item.MaBH }, new { onclick = "return ConfirmationDialog()" })
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("QLBaiHoc", new { page, @searchString = @ViewBag.SearchString }))

webTiengAnh/Views/BaiHoc/SearchBaiHoc.cshtml
@{
    ViewBag.Title = "SearchBaiHoc";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@model IEnumerable<webTiengAnh.Models.entity.BaiHoc>

<h2>Danh sách tìm kiếm bài học</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Mã Bài Học")
        </th>
        <th>
            @Html.DisplayName("Tên Bài Học")
        </th>
        <th>
            @Html.DisplayName("Chủ Đề")
        </th>
        <th>
            @Html.DisplayName("Ảnh Chủ Đề")
        </th>
        <th>
            @Html.DisplayName("Nội Dung 1")
        </th>
        <th>
            @Html.DisplayName("Nội Dung 2")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaBH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenBH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnhChuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungAnh)
            </td>
            <td>
                @Html.ActionLink("Sửa", "SuaHocSinh", new { id = item.MaBH }) |

                @Html.ActionLink("Xóa", "XoaHocSinh", new { id = item.MaBH })
            </td>
        </tr>
    }
</table>

webTiengAnh/Views/BaiHoc/SuaBaiHoc.cshtml
@model webTiengAnh.Models.entity.BaiHoc

@{
    ViewBag.Title = "SuaBaiHoc";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}





<h2>Sửa thông tin bài học</h2>
@section jsFooter{
    <script>
    $('#btnSelectImage').on('click', function (e) {
        e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction =function (url) {
                $('#txtAnhChuDe').val(url);
            };
            finder.popup();
    })
    $('#btnNoiDung').on('click', function (e) {
        e.preventDefault();
        var finder = new CKFinder();
        finder.selectActionFunction = function (url) {
            $('#txtNoiDung').val(url);
        };
        finder.popup();
    })
    $('#btnNoiDung2').on('click', function (e) {
        e.preventDefault();
        var finder = new CKFinder();
        finder.selectActionFunction = function (url) {
            $('#txtNoiDung2').val(url);
        };
        finder.popup();
    })
    </script>
}
@using (Html.BeginForm("EditActionBaiHoc", "BaiHoc"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaBH)

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên Bài Học")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenBH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenBH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Chủ đề")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.ChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChuDe, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Ảnh chủ đề")
            </div>
            @*<div class="col-md-5">
                @Html.EditorFor(model => model.AnhChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhChuDe, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AnhChuDe, new { htmlAttributes = new { @class = "form-control", @id = "txtAnhChuDe" }, id = "txtAnhChuDe" })
                <a id="btnSelectImage" href="#"> Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.AnhChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Nội dung 1")
            </div>
            @*<div class="col-md-5">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control", @id = "txtNoiDung" }, id = "txtNoiDung" })
                <a id="btnNoiDung" href="#"> Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Nội dung 2")
            </div>
            @*<div class="col-md-5">
                @Html.EditorFor(model => model.NoiDungAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDungAnh, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NoiDungAnh, new { htmlAttributes = new { @class = "form-control", @id = "txtNoiDung2" }, id = "txtNoiDung2" })
                <a id="btnNoiDung2" href="#"> Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.NoiDungAnh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("danh sách nghĩa từ")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.NghiaTu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NghiaTu, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("danh sách nghĩa từ 2")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.NghiaTu2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NghiaTu2, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Danh sách nghĩa từ 1")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.NoiDungAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDungAnh, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" onclick="confirmEdit()" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "QLBaiHoc")
</div>

webTiengAnh/Views/BaiHoc/ThemBaiHoc.cshtml
@model webTiengAnh.Models.entity.BaiHoc

@{
    ViewBag.Title = "ThemBaiHoc";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới bài học</h2>
@section jsFooter{
<script>
    $('#btnSelectImage').on('click', function (e) {
        e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction =function (url) {
                $('#txtAnhChuDe').val(url);
            };
            finder.popup();
    })
    $('#btnNoiDung').on('click', function (e) {
        e.preventDefault();
        var finder = new CKFinder();
        finder.selectActionFunction = function (url) {
            $('#txtNoiDung').val(url);
        };
        finder.popup();
    })
    $('#btnNoiDung2').on('click', function (e) {
        e.preventDefault();
        var finder = new CKFinder();
        finder.selectActionFunction = function (url) {
            $('#txtNoiDung2').val(url);
        };
    })
</script>
    }
@*<script>
    $(document).ready(function () {
        $('#btnSelectImage').on('click', function () {
            var finder = new CKFinder();
            finder.selectActionFunction =function (url) {
                $('#txtAnhChuDe').val(url);
            };
            finder.Popup();
        })
    })
</script>*@

@using (Html.BeginForm("AddBaiHoc", "BaiHoc"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Điền thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên Bài học")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenBH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenBH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Chủ đề")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.ChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Ảnh chủ đề")
            </div>
            @*<div class="col-md-5">
                @Html.EditorFor(model => model.AnhChuDe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhChuDe, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AnhChuDe, new { htmlAttributes = new { @class = "form-control", @id="txtAnhChuDe" } , id= "txtAnhChuDe" })
                <a id="btnSelectImage" href="#"> Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.AnhChuDe, "", new { @class = "text-danger" })
            </div>
        </div>
        @*@if (Model.TenBH == "Qua Hình Ảnh")
        {*@
            <div class="form-group">
                <div class="control-label col-md-2">
                    @Html.Label("Nội bài học 1")
                </div>
                @*<div class="col-md-5">
                        @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                    </div>*@

                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control", @id = "txtNoiDung" }, id = "txtNoiDung" })
                    <a id="btnNoiDung" href="#"> Chọn ảnh</a>
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    @Html.Label("Nội dung bài học 2")
                </div>
                @*<div class="col-md-5">
                        @Html.EditorFor(model => model.NoiDungAnh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NoiDungAnh, "", new { @class = "text-danger" })
                    </div>*@
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.NoiDungAnh, new { htmlAttributes = new { @class = "form-control", @id = "txtNoiDung2" }, id = "txtNoiDung2" })
                    <a id="btnNoiDung2" href="#"> Chọn ảnh</a>
                    @Html.ValidationMessageFor(model => model.NoiDungAnh, "", new { @class = "text-danger" })
                </div>
            </div>
        @*}
        else
        {*@
            @*<div class="control-label col-md-2">
                @Html.Label("Video")
                <div class="col-md-5">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>

            </div>*@
         @*}*@

                <div class="form-group">
                    <div class="control-label col-md-2">
                        @Html.Label("Danh sách nghĩa của từ");
                    </div>
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.NghiaTu, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NghiaTu, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-2">
                        @Html.Label("Danh sách nghĩa của từ 2");
                    </div>
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.NghiaTu2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NghiaTu2, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm mới" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

<div>
    @Html.ActionLink("Quay lại", "QLBaiHoc")
</div>