webTiengAnh/Models/entity/HocSinh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTiengAnh.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int MaHS { get; set; }
        public string TenHS { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string PhuHuynh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}

webTiengAnh/Controllers/HocSinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webTiengAnh.Models.entity;
using webTiengAnh.Models.DTO;
using webTiengAnh.Models.DAO;
using PagedList;

namespace webTiengAnh.Controllers
{
    public class HocSinhController : Controller
    {
        // GET: HocSinh
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Admin()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View();
            }
        }
        public ActionResult QLHocSinh(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                HocSinhDAo dao = new HocSinhDAo();
                IQueryable<HocSinh> hs = dao.DanhSachHS();
                return View(hs.OrderBy(n => n.MaHS).ToPagedList(pageNumber, pageSize));
            }
        }
        public ActionResult SearchStudent()
        {
            return View();
        }
        

        public ActionResult ThemHocSinh()
        {
            return View();
        }
        public ActionResult AddStd(HocSinhDTO hsa)
        {
            HocSinhDAo dao = new HocSinhDAo();
            dao.ThemHocSinh(hsa);
            return RedirectToAction("QLHocSinh");
        }
        public ActionResult SuaHocSinh(int id)
        {
            HocSinhDAo dao = new HocSinhDAo();
            HocSinh hs = dao.FindStudentById(id);
            return View(hs);
        }
        public ActionResult EditActionStd(HocSinh hsu)
        {
            HocSinhDAo dao = new HocSinhDAo();

            dao.SuaHocSinh(hsu);
            return RedirectToAction("QLHocSinh");
        }
        public ActionResult XoaHocSinh(int id)
        {
            HocSinhDAo dao = new HocSinhDAo();
            //HocSinh hs = dao.FindStudentById(id);
            dao.XoaHocSinh(id);

            return RedirectToAction("QLHocSinh");
        }

    }
}

webTiengAnh/Views/HocSinh/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Admin</h2>

webTiengAnh/Views/HocSinh/QLHocSinh.cshtml
@{
    ViewBag.Title = "QLHocSinh";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@model PagedList.IPagedList<webTiengAnh.Models.entity.HocSinh>
@using PagedList.Mvc;

<h2>Danh sách học sinh</h2>
<div class="panel-body">
    @using (Html.BeginForm("SearchStudent", "HocSinh"))
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-4">
                    <a type="button" class="btn btn-primary" href="/HocSinh/ThemHocSinh">Thêm học sinh</a>
                </div>
                <div class="col-md-3">
                    <input type="text" name="searchString" placeholder="Tìm kiếm" />
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success"> Tìm kiếm</button>
                </div>
            </div>

        </div>
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Ngày Sinh")
        </th>
        <th>
            @Html.DisplayName("Giới Tính")
        </th>
        <th>
            @Html.DisplayName("Địa Chỉ")
        </th>
        <th>
            @Html.DisplayName("Phụ huynh học sinh")
        </th>
        <th>
            @Html.DisplayName("Số liên lạc")
        </th>
        <th>
            @Html.DisplayName("Họ Tên")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhuHuynh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenHS)
            </td>
            <td>
                @Html.ActionLink("Sửa", "SuaHocSinh", new { id = item.MaHS }) |

                @Html.ActionLink("Xóa", "XoaHocSinh", new { id = item.MaHS }, new { onclick = "return ConfirmationDialog()" })
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("QLHocSinh", new { page, @searchString = @ViewBag.SearchString }))

webTiengAnh/Views/HocSinh/SearchStudent.cshtml
@{
    ViewBag.Title = "SearchStudent";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@model IEnumerable<webTiengAnh.Models.entity.HocSinh>

<h2>Danh sách tìm kiếm học sinh</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Họ và tên")
        </th>
        <th>
            @Html.DisplayName("Ngày sinh")
        </th>
        <th>
            @Html.DisplayName("Giới tính")
        </th>
        <th>
            @Html.DisplayName("Địa chỉ")
        </th>
        <th>
            @Html.DisplayName("Phụ huynh học sinh")
        </th>
        <th>
            @Html.DisplayName("Số liên lạc")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhuHuynh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.ActionLink("Sửa", "SuaHocSinh", new { id = item.MaHS }) |

                @Html.ActionLink("Xóa", "XoaHocSinh", new { id = item.MaHS })
            </td>
        </tr>
    }
</table>

webTiengAnh/Views/HocSinh/SuaHocSinh.cshtml
@model webTiengAnh.Models.entity.HocSinh

@{
    ViewBag.Title = "SuaHocSinh";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa thông tin học sinh</h2>

@using (Html.BeginForm("EditActionStd", "HocSinh"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHS)

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên Học Sinh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenHS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Ngày Sinh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Giới Tính")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên phụ huynh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.PhuHuynh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuHuynh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Địa Chỉ")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Số Điện Thoại")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" onclick="confirmEdit()" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "QLHocSinh")
</div>

webTiengAnh/Views/HocSinh/ThemHocSinh.cshtml
@model webTiengAnh.Models.entity.HocSinh

@{
    ViewBag.Title = "ThemHocSinh";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới học sinh</h2>

@using (Html.BeginForm("AddStd", "HocSinh"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Điền thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên học sinh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.TenHS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Ngày sinh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Giới tính")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Tên phụ huynh")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.PhuHuynh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhuHuynh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Địa chỉ")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Số điện thoại")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("UerName")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">
                @Html.Label("Mật khẩu")
            </div>
            <div class="col-md-5">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "QLHocSinh")
</div>